
'''Bulk contenant 32 sons
	
	statut 				F0
	ID					43
	Sous/statut/canal	0x
	Numero de format	09
	Nombre d'octets		20
	Nombre d'octets		00
	4096 données		xxxxxxxxxxxxxxxxxxxxxxxxxx
	Somme de contrôle	xx
	fin de sysex 		F7

Un timbre comprend 155 informations contenues dans 128 octets 

TAUX_EG_1_0P6
TAUX_EG_2_0P6
TAUX_EG 3_0P6
TAUX_EG_4_0P6
NIVEAU_EG_1_0P6
NIVEAU_EG_2_0P6
NIVEAU_EG 3_0P6
NIVEAU_EG_4_0P6
NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_0P6
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_0P6
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6
NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_0P6
NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_0P6
TAUX_PONDERATION_TOUCHES_ OP6
SENSIBILITE_MODULATION_AMPLITUDE_0P6
SENSIBILITE_VELOCITE_ TOUCHE_0P6
NIVEAU_SORTIE_OPERATEUR_OP6
MODE_OSCILLATEUR_OP6
FREQUENCE_GROSSIERE_OSCILLATEUR_OP6
FREQUENCE_FINE_OSCILLATEUR_OP6
DESACCORD_OSCILLATEUR_OP6 
TAUX_EG_1_OP5
TAUX_EG_2_OP5
TAUX_EG 3_OP5
TAUX_EG_4_OP5
NIVEAU_EG_1_OP5
NIVEAU_EG_2_OP5
NIVEAU_EG 3_OP5
NIVEAU_EG_4_OP5
NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP5
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP5
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6
NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP5
NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP5
TAUX_PONDERATION_TOUCHES_ OP6
SENSIBILITE_MODULATION_AMPLITUDE_OP5
SENSIBILITE_VELOCITE_ TOUCHE_OP5
NIVEAU_SORTIE_OPERATEUR_ OP5
MODE_OSCILLATEUR_ OP5
FREQUENCE_GROSSIERE_OSCILLATEUR_ OP5
FREQUENCE_FINE_OSCILLATEUR_ OP5
DESACCORD_OSCILLATEUR_ OP5
TAUX_EG_1_OP4
TAUX_EG_2_OP4
TAUX_EG 3_OP4
TAUX_EG_4_OP4
NIVEAU_EG_1_OP4
NIVEAU_EG_2_OP4
NIVEAU_EG 3_OP4
NIVEAU_EG_4_OP4
NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP4
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP4
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6
NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP4
NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP4
TAUX_PONDERATION_TOUCHES_ OP6
SENSIBILITE_MODULATION_AMPLITUDE_OP4
SENSIBILITE_VELOCITE_ TOUCHE_OP4
NIVEAU_SORTIE_OPERATEUR_ OP4
MODE_OSCILLATEUR_ OP4
FREQUENCE_GROSSIERE_OSCILLATEUR_ OP4
FREQUENCE_FINE_OSCILLATEUR_ OP4
DESACCORD_OSCILLATEUR_ OP4
TAUX_EG_1_OP3
TAUX_EG_2_OP3
TAUX_EG 3_OP3
TAUX_EG_4_OP3
NIVEAU_EG_1_OP3
NIVEAU_EG_2_OP3
NIVEAU_EG 3_OP3
NIVEAU_EG_4_OP3
NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP3
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP3
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6
NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP3
NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP3
TAUX_PONDERATION_TOUCHES_ OP6
SENSIBILITE_MODULATION_AMPLITUDE_OP3
SENSIBILITE_VELOCITE_ TOUCHE_OP3
NIVEAU_SORTIE_OPERATEUR_ OP3
MODE_OSCILLATEUR_ OP3
FREQUENCE_GROSSIERE_OSCILLATEUR_ OP3
FREQUENCE_FINE_OSCILLATEUR_ OP3
DESACCORD_OSCILLATEUR_ OP3
TAUX_EG_1_OP2
TAUX_EG_2_OP2
TAUX_EG 3_OP2
TAUX_EG_4_OP2
NIVEAU_EG_1_OP2
NIVEAU_EG_2_OP2
NIVEAU_EG 3_OP2
NIVEAU_EG_4_OP2
NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP2
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP2
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6
NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP2
NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP2
TAUX_PONDERATION_TOUCHES_ OP6
SENSIBILITE_MODULATION_AMPLITUDE_OP2
SENSIBILITE_VELOCITE_ TOUCHE_OP2
NIVEAU_SORTIE_OPERATEUR_ OP2
MODE_OSCILLATEUR_ OP2
FREQUENCE_GROSSIERE_OSCILLATEUR_ OP2
FREQUENCE_FINE_OSCILLATEUR_ OP2
DESACCORD_OSCILLATEUR_ OP2
TAUX_EG_1_OP1
TAUX_EG_2_OP1
TAUX_EG 3_OP1
TAUX_EG_4_OP1
NIVEAU_EG_1_OP1
NIVEAU_EG_2_OP1
NIVEAU_EG 3_OP1
NIVEAU_EG_4_OP1
NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP1
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP1
NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6
NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP1
NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP1
TAUX_PONDERATION_TOUCHES_ OP6
SENSIBILITE_MODULATION_AMPLITUDE_OP1
SENSIBILITE_VELOCITE_ TOUCHE_OP1
NIVEAU_SORTIE_OPERATEUR_ OP1
MODE_OSCILLATEUR_ OP1
FREQUENCE_GROSSIERE_OSCILLATEUR_ OP1
FREQUENCE_FINE_OSCILLATEUR_ OP1
DESACCORD_OSCILLATEUR_ OP1
TAUX_HAUTEUR_EG_1
TAUX_HAUTEUR_EG_2
TAUX_HAUTEUR_EG_3
TAUX_HAUTEUR_EG_4
NIVEAU_HAUTEUR_EG_ I
NIVEAU_HAUTEUR_EG_ 2
NIVEAU_HAUTEUR_EG_ 3
NIVEAU_HAUTEUR_EG_ 4
SELECTION_ALGORITHME
RETROACTION
SYNCHRONISATION_TOUCHE_OSCI LLATEUR
VITESSE_LFG
RETARD_LFG
PROFONDEUR_MODULATION_ HAUTEUR_LFO
PROFONDEUR _MODULATION_AMPLITUDE_LFO
SYNCHRONISATION_TOUCHE_LFO
FORME_ONDE_LFO
SENSIBILITE_MODULATION_HAUTEUR_LFO
TRANSPOSITION
NOM_TIMBRE_1
NOM_TIMBRE_1
NOM_TIMBRE_1
NOM_TIMBRE_1
NOM_TIMBRE_1
NOM_TIMBRE_1
NOM_TIMBRE_1
NOM_TIMBRE_1
NOM_TIMBRE_1
NOM_TIMBRE_10




'''
#Liste des 155 paramètres 
parametre=['TAUX_EG_1_0P6','TAUX_EG_2_0P6','TAUX_EG_3_0P6','TAUX_EG_4_0P6','NIVEAU_EG_1_0P6','NIVEAU_EG_2_0P6','NIVEAU_E_3_0P6','NIVEAU_EG_4_0P6','NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_0P6',
'NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_0P6','NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6','NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_0P6',
'NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_0P6','TAUX_PONDERATION_TOUCHES_ OP6','SENSIBILITE_MODULATION_AMPLITUDE_0P6','SENSIBILITE_VELOCITE_ TOUCHE_0P6',
'NIVEAU_SORTIE_OPERATEUR_OP6','MODE_OSCILLATEUR_OP6','FREQUENCE_GROSSIERE_OSCILLATEUR_OP6','FREQUENCE_FINE_OSCILLATEUR_OP6','DESACCORD_OSCILLATEUR_OP6 ','
'TAUX_EG_1_OP5','TAUX_EG_2_OP5','TAUX_EG_3_OP5','TAUX_EG_4_OP5','NIVEAU_EG_1_OP5','NIVEAU_EG_2_OP5','NIVEAU_EG_3_OP5','NIVEAU_EG_4_OP5','NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP5',
'NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP5','NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6','NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP5',
'NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP5','TAUX_PONDERATION_TOUCHES_ OP6','SENSIBILITE_MODULATION_AMPLITUDE_OP5','SENSIBILITE_VELOCITE_ TOUCHE_OP5',
'NIVEAU_SORTIE_OPERATEUR_ OP5','MODE_OSCILLATEUR_ OP5','FREQUENCE_GROSSIERE_OSCILLATEUR_ OP5','FREQUENCE_FINE_OSCILLATEUR_ OP5','DESACCORD_OSCILLATEUR_ OP5',
'TAUX_EG_1_OP4','TAUX_EG_2_OP4','TAUX_EG_3_OP4','TAUX_EG_4_OP4','NIVEAU_EG_1_OP4','NIVEAU_EG_2_OP4','NIVEAU_EG_3_OP4','NIVEAU_EG_4_OP4','NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP4',
'NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP4','NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6','NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP4',
'NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP4','TAUX_PONDERATION_TOUCHES_ OP6','SENSIBILITE_MODULATION_AMPLITUDE_OP4','SENSIBILITE_VELOCITE_ TOUCHE_OP4',
'NIVEAU_SORTIE_OPERATEUR_ OP4','MODE_OSCILLATEUR_ OP4','FREQUENCE_GROSSIERE_OSCILLATEUR_ OP4','FREQUENCE_FINE_OSCILLATEUR_ OP4','DESACCORD_OSCILLATEUR_ OP4',
'TAUX_EG_1_OP3','TAUX_EG_2_OP3','TAUX_EG_3_OP3','TAUX_EG_4_OP3','NIVEAU_EG_1_OP3','NIVEAU_EG_2_OP3','NIVEAU_EG_3_OP3','NIVEAU_EG_4_OP3','NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP3',
'NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP3','NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6','NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP3',
'NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP3','TAUX_PONDERATION_TOUCHES_ OP6','SENSIBILITE_MODULATION_AMPLITUDE_OP3','SENSIBILITE_VELOCITE_ TOUCHE_OP3',
'NIVEAU_SORTIE_OPERATEUR_ OP3','MODE_OSCILLATEUR_ OP3','FREQUENCE_GROSSIERE_OSCILLATEUR_ OP3','FREQUENCE_FINE_OSCILLATEUR_ OP3','DESACCORD_OSCILLATEUR_ OP3',
'TAUX_EG_1_OP2','TAUX_EG_2_OP2','TAUX_EG_3_OP2','TAUX_EG_4_OP2','NIVEAU_EG_1_OP2','NIVEAU_EG_2_OP2','NIVEAU_EG_3_OP2','NIVEAU_EG_4_OP2','NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP2',
'NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP2','NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6','NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP2',
'NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP2','TAUX_PONDERATION_TOUCHES_ OP6','SENSIBILITE_MODULATION_AMPLITUDE_OP2','SENSIBILITE_VELOCITE_ TOUCHE_OP2',
'NIVEAU_SORTIE_OPERATEUR_ OP2','MODE_OSCILLATEUR_ OP2','FREQUENCE_GROSSIERE_OSCILLATEUR_ OP2','FREQUENCE_FINE_OSCILLATEUR_ OP2','DESACCORD_OSCILLATEUR_ OP2',
'TAUX_EG_1_OP1','TAUX_EG_2_OP1','TAUX_EG_3_OP1','TAUX_EG_4_OP1','NIVEAU_EG_1_OP1','NIVEAU_EG_2_OP1','NIVEAU_EG_3_OP1','NIVEAU_EG_4_OP1','NIVEAU_PONDERATION_TOUCHES_POINT_ARRET_OP1',
'NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_GAUCHE_OP1','NIVEAU_PONDERATION_TOUCHES_AMPLITUDE_DROITE_OP6','NIVEAU_PONDERATION_TOUCHES_COURBE_ GAUCHE_OP1','NIVEAU_PONDERATION_TOUCHES_COURBE_ DROITE_OP1',
'TAUX_PONDERATION_TOUCHES_ OP6','SENSIBILITE_MODULATION_AMPLITUDE_OP1','SENSIBILITE_VELOCITE_ TOUCHE_OP1','NIVEAU_SORTIE_OPERATEUR_ OP1','MODE_OSCILLATEUR_ OP1',
'FREQUENCE_GROSSIERE_OSCILLATEUR_ OP1','FREQUENCE_FINE_OSCILLATEUR_ OP1','DESACCORD_OSCILLATEUR_ OP1','TAUX_HAUTEUR_EG_1','TAUX_HAUTEUR_EG_2','TAUX_HAUTEUR_EG_3',
'TAUX_HAUTEUR_EG_4','NIVEAU_HAUTEUR_EG_1','NIVEAU_HAUTEUR_EG_2','NIVEAU_HAUTEUR_EG_3','NIVEAU_HAUTEUR_EG_4','SELECTION_ALGORITHME','RETROACTION',
'SYNCHRONISATION_TOUCHE_OSCILLATEUR','VITESSE_LFG','RETARD_LFG','PROFONDEUR_MODULATION_ HAUTEUR_LFO','PROFONDEUR _MODULATION_AMPLITUDE_LFO',
'SYNCHRONISATION_TOUCHE_LFO','FORME_ONDE_LFO','SENSIBILITE_MODULATION_HAUTEUR_LFO','TRANSPOSITION','NOM_TIMBRE_1','NOM_TIMBRE_2','NOM_TIMBRE_3','NOM_TIMBRE_4',
'NOM_TIMBRE_5','NOM_TIMBRE_6','NOM_TIMBRE_7','NOM_TIMBRE_8','NOM_TIMBRE_9','NOM_TIMBRE_10']

valeur_max_parametre=[99,99,99,99,99,99,99,99,99,99,99,3,3,14,7,7,3,99,31,99,99,99,99,99,99,99,99,99,99,99,99,3,3,14,7,7,3,99,31,99,99,99,99,99,99,99,99,99,99,99,99,3,3,14,7,7,3,99,31,99,99,99,99,99,99,99,99,99,99,99,99,3,3,14,7,7,3,99,31,99,99,99,99,99,99,99,99,99,99,99,99,3,3,14,7,7,3,99,31,99,99,99,99,99,99,99,99,99,99,99,99,3,3,14,7,7,3,99,31,99,99,99,99,99,99,99,99,99,31,1,7,99,99,99,99,7,5,1,48,255,255,255,255,255,255,255,255,255,255]

# dans le bloc de 128 octects d'un programme, certains sont à éclater pour en extraire les 2 ou 3 valeurs qu'il contient
# ce sont les octets : 
# 11 (RC, LC), 12 (PD, RS), 13 (KVS, AMS), 15 (FC, M) pour l'opérateur 6  
# 11+17 (RC, LC), 12+17 (PD, RS), 13 (KVS, AMS), 15 (FC, M) pour l'opérateur 5
# 11+34 (RC, LC), 12+34 (PD, RS), 13 (KVS, AMS), 15 (FC, M) pour l'opérateur 4
# 11+51 (RC, LC), 12+51 (PD, RS), 13 (KVS, AMS), 15 (FC, M) pour l'opérateur 3
# 11+68 (RC, LC), 12+68 (PD, RS), 13 (KVS, AMS), 15 (FC, M) pour l'opérateur 2
# 11+85 (RC, LC), 12+85 (PD, RS), 13 (KVS, AMS), 15 (FC, M) pour l'opérateur 1

# 110 (ALS)
# 111 (OKS, FB)
# 116 (LPMS, LFW,LKFS)

R1_OP6=0,
R2_OP6,1,
R3_OP6,2,
R4_OP6,3,
L1_OP6,4,
L2_OP6,5,
L3_OP6,6,
L4_OP6,7,
BP_OP6,8,
lD_OP6,9,
RD_OP6,10,
RC_OP6,11,
LC_OP6,11,
PD_OP6,12,
RS_OP6,12,
KVS_OP6,13,
AMS_OP6,13,
OL_OP6,14
FC_OP6,15, 
M_OP6,15,
FF_OP5, 
R1_OP5,
R2_OP5,
R3_OP5,
R4_OP5,
L1_OP5,
L2_OP5,
L3_OP5,
L4_OP5,
BP_OP5,
lD_OP5,
RD_OP5,
RC_OP5,
LC_OP5,
PD_OP5,
RS_OP5,
KVS_OP5,
AMS_OP5,
OL_OP5,
FC_OP5, 
M_OP5,
FF_OP5, 
R1_OP4,
R2_OP4,
R3_OP4,
R4_OP4,
L1_OP4,
L2_OP4,
L3_OP4,
L4_OP4,
BP_OP4,
lD_OP4,
RD_OP4,
RC_OP4,
LC_OP4,
PD_OP4,
RS_OP4,
KVS_OP4,
AMS_OP4,
OL_OP4,
FC_OP4, 
M_OP4,
FF_OP4, 
R1_OP3,
R2_OP3,
R3_OP3,
R4_OP3,
L1_OP3,
L2_OP3,
L3_OP3,
L4_OP3,
BP_OP3,
lD_OP3,
RD_OP3,
RC_OP3,
LC_OP3,
PD_OP3,
RS_OP3,
KVS_OP3,
AMS_OP3,
OL_OP3,
FC_OP3, 
M_OP3,
FF_OP3, 
R1_OP2,
R2_OP2,
R3_OP2,
R4_OP2,
L1_OP2,
L2_OP2,
L3_OP2,
L4_OP2,
BP_OP2,
lD_OP2,
RD_OP2,
RC_OP2,
LC_OP2,
PD_OP2,
RS_OP2,
KVS_OP2,
AMS_OP2,
OL_OP2,
FC_OP2, 
M_OP2,
FF_OP2, 
R1_OP1,
R2_OP1,
R3_OP1,
R4_OP1,
L1_OP1,
L2_OP1,
L3_OP1,
L4_OP1,
BP_OP1,
lD_OP1,
RD_OP1,
RC_OP1,
LC_OP1,
PD_OP1,
RS_OP1,
KVS_OP1,
AMS_OP1,
OL_OP1,
FC_OP1, 
M_OP1,
FF_OP1,
PR1,102,
PR2,103,
PR3,104,
PR4,105,
PL1,106,
PL2,107,
PL3,108,
PL4,109,
ALS,110
OKS,111,
FB,111,
LFS,112,
LFD,113,
LPMD,114,
LAMD,115,
LPMS,116,
LFW,116,
LKFS,116,
TRNP,117
VNAM1,118,
VNAM2,119,
VNAM3,120,
VNAM4,121,
VNAM5,122,
VNAM6,123,
VNAM7,124,
VNAM8,125,
VNAM9,126,
VNAM10,127
